### ISSUE TITLE
[TODO] model.pt to object storage service

### ISSUE THREAD

**Issue by SeongIkKim** [cheat-tos/serving#10]
## 📌  요약

- (수행 전) 학습 후 model 파일 object storage로 저장하도록 train.py를 수정하려고 합니다.

- (수행 후) 결과는 어땠는지

### Before

-

### After

-

**Comment by ddooom** [comment]
object storage로 저장하는게 어디로 저장하는 것인지 알 수 있을까요??

**Comment by SeongIkKim** [comment]
@ddooom
현재는 mlflow의 tracking server처럼 학습한 모델들 따로 관리하는 모델들을 사용하고 있지 않기때문에, AWS s3와 같은 저장소에 학습된 model.pt파일의 replica를 저장해두고 versioning하려고 합니다!

**Comment by SeongIkKim** [comment]
계획 변경되어서 close하겠습니다!
