### ISSUE TITLE
[TODO] BentoML Inference server 로드밸런싱

### ISSUE THREAD

**Issue by SeongIkKim** [cheat-tos/serving#13]
## 📌  요약

- (수행 전) flask로 들어온 요청을 여러 포트로 로드밸런싱하는 Nginx를 추가합니다.

- (수행 후) Nginx나 Traefik 대신 Docker Swarm을 사용합니다.

### Before

- ~~Nginx는 로드밸런서 역할을 하여, 하나의 포트로 들어온 요청을 여러 포트로 분산시켜 보낼수 있습니다.~~
  - Nginx는 컨테이너에 적합하게 설계된 로드밸런서가 아니므로, traefik을 사용해봅니다.
- 이를 이용하여, 많은 사용자의 요청을 처리하도록 Inference 서버를 늘릴 수 있습니다.(docker compose --scale 옵션)
- 또, 새로운 데이터로 재학습된 컨테이너를 바꿔치기하는동안 기존의 서버가 계속 요청을 처리하도록 할 수 있습니다.

### After

- Docker swarm을 사용하기로 하여 기존의 로드밸런서 건을 폐기합니다!

---

### Reference

- https://stackoverflow.com/questions/39168239/update-only-one-container-via-docker-compose
- https://www.atlantic.net/vps-hosting/how-to-update-docker-container-with-zero-downtime/
- https://coderbook.com/@marcus/how-to-do-zero-downtime-deployments-of-docker-containers/

**Comment by wjdgns7712** [comment]
👍
