### ISSUE TITLE
[TODO] 컨테이너 오케스트레이션 툴로 로드밸런싱과 롤링 업데이트 수행

### ISSUE THREAD

**Issue by SeongIkKim** [cheat-tos/serving#16]
## 📌  요약

- (수행 전) 하나의 flask 서버로 들어온 요청에 대하여 Load Balancing과 fail over check, Rolling update까지 수행할 수 있는 오케스트레이션 툴을 사용합니다.

- (수행 후) 

### Before

- 러닝커브가 낮은 Docker Swarm 사용예정이며, 사실상 데모 시연용이므로 EC2 서버에 배포하는 형태는 그대로 가져갑니다.
- 원래 올바른 부하분산을 위해서는 워커 노드를 각각 다른 EC2나 컨테이너 서비스에 할당하는것이 맞지만, 현재 아키텍쳐에서는 무리가 있으므로 차선책을 선택했습니다.

### After

![스크린샷 2021-06-18 오전 3 33 18](https://user-images.githubusercontent.com/26772420/122454088-f03e3080-cfe5-11eb-8582-c9273a35ad48.png)
- 리소스 부족으로 inference 컨테이너가 생성이 안되어 플랫폼을 옮기거나, 그냥 조금 더 큰 인스턴스를 사용할 예정입니다.

---

### Reference

- https://roseline124.github.io/kuberdocker/2019/08/02/docker-study10.html

**Comment by wjdgns7712** [comment]
👍
