### ISSUE TITLE
[TODO] BentoML 리뷰

### ISSUE THREAD

**Issue by SeongIkKim** [cheat-tos/serving#4]
## 📌  요약

- (수행 전) Production service에 올리기는 MLflow보다 BentoML이 낫다던데, 일단 MLflow로 먼저 올려보고 차이점 알아보기.

- (수행 후) BentoML은 실제 많은 기능을 제공하였으며, 이번 프로젝트 서빙에서 주축이 되는 프레임워크로 사용

### Before

- API Swagger docs까지 제공해주는건 좋은데.. 굳이 두개나 툴을 배울필요가 있을까?
- https://dailyheumsi.tistory.com/256?category=980484

### After

# BentoML Review

### @bentoml.env()

- 서버에서 사용되는 라이브러리를 입력하는 데코레이터
- 서버에서 사용되는 라이브러리들을 추론하여 requirement 파일을 만들어준다.
    - 기존의 requirement.txt를 사용하여 만들 수도 있으며, 라이브러리 이름을 직접 입력하여 만들 수도 있다.

### @bentoml.artifacts()

- 서버에서 사용되는 모델 파일, json 파일, pickle 파일 등을 저장해주는 데코레이터
- baseline lstm을 사용할 때, 필요한 artifacts
    1. 학습되어 있는 모델 파일, model.pt
    2. inference 시 예측할 test data, pandas dataframe type으로 pickle로 저장
    3. 모델 학습, 데이터 전처리 등에서 사용되는 config 파일, json 파일
    4. test dataset의 categorical feature를  training dataset과 같이 label encoding해줄 np.array type, pickle로 저장

        (assessmentItemID_classes, testId_classes, KnowledgeTag_classes)

### @bento.api()

- 해당 url에 접속하였을 때, 실행되는 함수에서 input 또는 batch process를 설정해주는 데코레이터
- 해당 데코레이터 다음에 나오는 함수 명이 url 명이 된다.

    ex) 함수명 : predict, url : 0.0.0.0:port/predict

### packing

- `@bento.artifact()` 에서 설정한 artifacts들을 `[bento class].pack()`으로 packing 해주고 `save()`를 해주면 최신 버전의 디렉토리가 생성된다.

### Imported py files

- bentoml에서 env, artifacts 등을 설정하는 파일이나 packing 해주는 파일에서 import하는 다른 python 파일들은 bentoml에서 추적하여 서버에 저장해준다.
- import하는 python 파일이 다른 디렉토리에 있는 경우에는 해당 디렉토리에서 여러 python 파일을 init.py로 묶어줘야 디렉토리 전체가 서버에 저장된다.

### Serving

- CLI에서 `bentoml serve [bento class]:latest` 를 입력하여 serving
- `—-port`를 통해 port 번호 설정 가능
- 아래 코드를 통해 파이썬에서 테스트 가능

    ```python
    res = requests.post('http://0.0.0.0:5000/predict', json= data)
    print(res.text)
    ```

### Docker

- 서버가 생성되면 디렉토리 안에 자동으로 docker file이 생성된다.
- 해당 docker로 이미지 생성 가능

### HTML Rendering

- HTML로 Rendering 기능은 없기에 flask를 이용
- flask로 렌더링하여 데이터를 받고 `requests.post`로 데이터를 bentoml로 post한 뒤 결과를 받아 다시 랜더링하는 방식

**Comment by ddooom** [comment]
감사합니다! 참고하겠습니당

**Comment by SeongIkKim** [comment]
개인적으로는 API Swagger tool도 좋지만, packing 즉시 dockerfile까지 만들어준다는건 정말 어마어마한 장점이라고 생각되네요..!
