### ISSUE TITLE
[TODO] flask server html 수정

### ISSUE THREAD

**Issue by SeongIkKim** [cheat-tos/serving#7]
## 📌  요약

- (수행 전) 기존 데일리미션 템플릿에서 벗어나서 의미있는 수준의 템플릿으로 바꿔볼까 합니다.

- (수행 후) 결과는 어땠는지

### Before

- 레퍼런스로 산타토익은 어떨까요..?

- Flask에서 기존의 q_content,  tag, test_id, assess_id, answer 정보만 받아오는 형태

![image](https://user-images.githubusercontent.com/48445695/121767912-48180a00-cb96-11eb-9913-79e833e51414.png)

### After

- FE에 필요한 중요한 정보인 문제를 풀었을 당시의 timestamp를 추가로 받아옴

![image](https://user-images.githubusercontent.com/48445695/121767925-5c5c0700-cb96-11eb-8d83-440e51fb2627.png)

- date format을 사용자가 편하게 수정하기 위해 moment 라이브러리 사용.

![image](https://user-images.githubusercontent.com/48445695/121767969-8e6d6900-cb96-11eb-820b-fa9cbf427ad9.png)

**Comment by wjdgns7712** [comment]
추가로 산타토익 혹은 i-scream edu 페이지를 참고하여 ui design 수정예정
