### ISSUE TITLE
[TODO] Airflow DAG Mockup

### ISSUE THREAD

**Issue by SeongIkKim** [cheat-tos/serving#8]
## 📌  요약

- (수행 전) Airflow가 수행하는 ETL - Train - Inference 과정을 DAG로 어떻게 짤 것인지 mockup을 논의합니다.

- (수행 후) 결과는 어땠는지

### Before

-

### After

![image](https://user-images.githubusercontent.com/48445695/122419718-15bb4200-cfc6-11eb-81a1-156f91cf72ba.png)

**Comment by wjdgns7712** [comment]
Dag Task : DataLoad >> Retrain >> Packing >> Drop&Reload

**Comment by SeongIkKim** [comment]
#14 에서 처리했습니다.
